language: node_js
node_js:
  - "node"
  - "12"
sudo: required
script: "true"

install:
  - cd back-end/
  - npm install
  - npm run 
  - cd ../front-end
  - npm install
  - npm run

services:
  - mongodb
  
script:
  - unit-tests

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
